export const GET_IS_FAVORITES = 'GET_IS_FAVORITES';
export const GET_IS_FAVORITES_SUCCESS = 'GET_IS_FAVORITES_SUCCESS';
export const GET_IS_FAVORITES_FAIL = 'GET_IS_FAVORITES_FAIL';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAIL = 'ADD_TO_FAVORITES_FAIL';

export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_FAIL = 'REMOVE_FROM_FAVORITES_FAIL';
